"$schema" = "./node_modules/wrangler/config-schema.json"
main = ".open-next/worker.js"
name = "bedrinth"
# Set this to today's date
compatibility_date = "2026-02-19"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"